### ISSUE TITLE
Better anti bot functionality

### ISSUE THREAD

**Issue by Darin755** [sequentialread/pow-bot-deterrent#1]
Hello,
I'm still learning so this may be a flawed idea.

Would it be possible to create some sort of forced delay for repeated attempts by the client? Many smart phones will make you wait after a curtain number of login attempts and I though it might be possible to do something similar here.

This could be a awful idea but I am still glad that this project exists.

Cheers, 

Darin755

**Comment by ForestJohnson** [comment]
The smartphone pin lock is based on a hardware chip built into the phone.    Its not possible on a website unless the user already has an account (for example this is how debit card PINs work)
